config/routes.rb
Hhreboot2::Application.routes.draw do
  
  resources :messages
  
  mount Forem::Engine, :at => "/forums"
  devise_for :users, :controllers => {:registrations => "registrations", confirmations: "confirmations"}

#  root :to => 'navigation#homepage'
  root :to => 'navigation#alt_homepage'
  
  match 'new_topics' => 'topics#new_topics'

  match 'owner_area' => 'owner#owner_area'
  match 'insert_class' => 'owner#insert_class'
  match 'custom_script' => 'owner#custom_script'
  match 'review_test_bank_entries' => 'owner#review_test_bank_entries'
  match 'lock_account' => 'owner#lock_account'
  match 'unlock_account' => 'owner#unlock_account'
  
  match 'homepage' => 'navigation#alt_homepage'
  match 'hot_topics' => 'navigation#hot_topics'
  match 'newest_topics' => 'navigation#newest_topics'
  match 'building_leaders' => 'navigation#building_leaders'
  match 'add_major_minor' => 'navigation#add_major_minor'
  match 'top_posters' => 'navigation#top_posters'
  match 'sandbox' => 'navigation#sandbox'
  match 'update_courses' => 'navigation#update_courses'
  match 'about' => 'navigation#about'
  match 'roadmap' => 'navigation#roadmap'
  match 'dining_menu' => 'navigation#dining_menu'

  match 'test_bank' => 'exams#test_bank'
  match 'upvote' => 'exams#upvote'
  match 'downvote' => 'exams#downvote'
  match 'submit_vote' => 'exams#submit_vote'
  match 'my_vault' => 'exams#my_vault'
  match 'upload_exam' => 'exams#upload_exam'
  match 'upload_page' => 'exams#upload_page'
  match 'download_exam' => 'exams#download_exam'
  match 'inspect_exams' => 'exams#inspect_exams'
  match 'grant_access' => 'exams#grant_access'

  match 'my_messages' => 'messages#my_messages'
  match 'create_message' => 'messages#create'
  match 'view_message' => 'messages#view_message'
  match 'reply_to_message' => 'messages#reply_to_message'
  match 'trash_message' => 'messages#trash_message'
  match 'restore_message' => 'messages#restore_message'
  match 'destroy_message' => 'messages#destroy'
  
  match 'user_profile' => 'users#alt_profile'
  match 'alt_profile' => 'users#alt_profile'
  match 'classmates' => 'users#classmates'
  match 'modify_profile' => 'users#modify_profile'
  match 'add_major_minors' => 'users#add_major_minors'
  match 'add_friend' => 'friendships#create'

  match 'destroy_quarter' => 'quarters#destroy'
  match 'list_fields' => 'fields#list'
  match 'input_course_data' => 'courses#add_data'
  
  match 'my_library' => 'library#my_library'  
  match 'add_book' => 'library#add_book'  
  match 'destroy_book' => 'library#destroy'  
  match 'find_trades' => 'library#find_trades'  
  match 'find_books' => 'library#find_books'  
  match 'three_way_trades' => 'library#three_way_trades'  
  match 'manage_textbooks' => 'library#manage_textbooks'  
  
  match 'list_courses' => 'courses#list'
  match 'add_course_to_quarter' => 'courses#add_course_to_quarter'
  match 'remove_course_from_quarter' => 'courses#remove_course_from_quarter'
  match 'manage_classes' => 'courses#manage_classes'

  match 'building_page' => 'buildings#building_page'

  
#  match 'add_courses' => 'courses#add_data'
#  match 'add_buildings' => 'buildings#add_data'

  
  
end

app/controllers/navigation_controller.rb
class NavigationController < ApplicationController

	require 'open-uri'

	def homepage
		respond_to do |format|
			format.html
		end
	end
	
	def alt_homepage
		@subtitles = 
			["Your ResHall Resource"]
		@rand_subtitle = @subtitles[rand(@subtitles.count)]
		respond_to do |format|
			format.html
			format.js
		end
	end
	
	def hot_topics	
		respond_to do |format|
			format.html
		end
	end
	
	def newest_topics	
		@topics = Forem::Topic.all
	
		respond_to do |format|
			format.html
		end
	end
	
	def building_leaders	
		respond_to do |format|
			format.html
		end
	end
	
	def top_posters	
		respond_to do |format|
			format.html
		end
	end
	
	def add_major_minor
		respond_to do |format|
			format.html
			format.json { render :json => @users}
		end
	end

	def about
		respond_to do |format|
			format.html
		end		
	end

	def roadmap
		respond_to do |format|
			format.html
		end
	end
	
	def sandbox
		if current_user.quarters.where(:term => "Fall 2012")
			@my_courses = current_user.quarters.where(:term => "Fall 2012").first.courses
		end
		@fields = Field.all
		@courses = Course.all
		if params["field"]
			@course_list = Field.find(params["field"]).courses
		end
		
		respond_to do |format|
			format.html
			format.json { render :json => @users}
			format.js
		end
	end

	def dining_menu
		respond_to do |format|
			format.html
		end
	end
	
end

app/views/navigation/_add_major_minor.html.erb
  <div>
  Major 2:</br>
  <%= collection_select(:user, :major, Field.all, :title, :title) %></br>
  </div></br>
  
  <div>
  Minor:</br>
  <%= collection_select(:user, :major, Field.all, :title, :title) %></br>
  </div></br>
  
  <div>
  Minor 2:</br>
  <%= collection_select(:user, :major, Field.all, :title, :title) %></br>
  </div></br>

app/views/navigation/_dining.html.erb
<% url = "http://menu.ha.ucla.edu/foodpro/default.asp" %>
<% doc = Nokogiri::HTML(open(url)) %>

<div id="dining_wrapper">
	<span id="close">X</span>
	<div id="title"><%= Date.today.to_formatted_s(:long_ordinal) %></div>
	<div class="lunch">
		<div id="mealtime">Lunch</div>
		<hr>

		<div class="dhall">
			<div class="dhall_names">Covel</div>
			<% doc.css("#menuwrapper :nth-child(1) .menugridtable .menugridcell:nth-child(1)").css(".level5 a").each do |menu_item| %>
				-<%= menu_item.text %></br>
			<% end %>
		</div>

		<div class="dhall">
			<div class="dhall_names">De Neve</div>
			<% doc.css("#menuwrapper :nth-child(1) .menugridtable .menugridcell:nth-child(2)").css(".level5 a").each do |menu_item| %>
				-<%= menu_item.text %></br>
			<% end %>
		</div>

		<div class="dhall">
			<div class="dhall_names">Feast</div>
			<% doc.css("#menuwrapper :nth-child(1) .menugridtable .menugridcell_last").css(".level5 a").each do |menu_item| %>
				-<%= menu_item.text %></br>
			<% end %>
		</div>		
	</div>

	<div class="dinner">
		<div id="mealtime">Dinner</div>
		<hr>
		<div class="dhall">
			<div class="dhall_names">Covel</div>
			<% doc.css("#menuwrapper :nth-child(4) .menugridtable .menugridcell:nth-child(1)").css(".level5 a").each do |menu_item| %>
					-<%= menu_item.text %></br>
			<% end %>
		</div>

		<div class="dhall">
			<div class="dhall_names">De Neve</div>
			<% doc.css("#menuwrapper :nth-child(4) .menugridtable .menugridcell:nth-child(2)").css(".level5 a").each do |menu_item| %>
				-<%= menu_item.text %></br>
			<% end %>
		</div>

		<div class="dhall">
			<div class="dhall_names">Feast</div>
			<% doc.css("#menuwrapper :nth-child(4) .menugridtable .menugridcell_last").css(".level5 a").each do |menu_item| %>
				-<%= menu_item.text %></br>
			<% end %>
		</div>
	</div>

</div>

app/views/navigation/_my_courses.html.erb
<%= content_tag_for(:tr, @my_courses) do |course| %>
  <td class="course_title"><%= course.title %></td>
  <td><%= link_to "Remove", remove_course_from_quarter_path(:crs_id => course.id, :qtr_id => current_user.quarters.where(:term => "Fall 2012").first, :d_id => dom_id(course)), :remote => true %></td>
<% end %>

app/views/navigation/_newest_users.html.erb
<% users = User.where("username != ?", "Anonymous") %>
<% users.sort! { |a,b| b.created_at <=> a.created_at } %>
<% list_num = 1 %>

<div class="right_widget" id="top_contributors">
	<div id="title">Newest Members</div>

<table align="center">
	<col width="10%" />
	<col width="70%" />
	<tr>
	<td></td>
	<td>Username</td>
	</tr>
	<% users.each do |u| %>
		<tr>
			<td><%= list_num %>. </td>
			<td align="left"><%= link_to u.username, user_profile_path(:user => u.id) %></td>
		</tr>
		<% list_num = list_num + 1 %>
		<% if list_num > 10; break; end %>
	<% end %>
</table>
</div>

app/views/navigation/_test_bank_uploads.html.erb
<% tests = Exam.all %>
<% tests.sort! { |a,b| b.created_at <=> a.created_at } %>
<% tests = tests.first(10) %>
<% list_num = 1 %>

<div class="right_widget" id="top_contributors">
	<div id="title">Test Bank Uploads</div>

<table align="center">
	<col width="10%" />
	<col width="70%" />
	<tr>
	<td></td>
	<td>File Name</td>
	</tr>
	<% tests.each do |t| %>
		<tr>
			<td><%= list_num %>. </td>
			<td align="left"><%= link_to "#{t.document_file_name.first(18)}...", test_bank_path(:course => t.course.id) %></td>
		</tr>
		<% list_num = list_num + 1 %>
		<% if list_num > 10; break; end %>
	<% end %>
</table>
</div>

app/views/navigation/_top_posters.html.erb
<!-- Top Posters -->
<% users = User.where("username != ?", "Anonymous") %>
<% users.sort! { |a,b| b.posts.count <=> a.posts.count } %>
<% list_num = 1 %>

<div class="right_widget" id="top_contributors">
	<div id="title">Top Contributors</div>

<table align="center">
	<col width="10%" />
	<col width="70%" />
	<col width="20%" />
	<tr>
	<td></td>
	<td>Username</td>
	<td>Posts</td>
	</tr>
	<% users.each do |u| %>
		<tr>
			<td><%= list_num %>. </td>
			<td align="left"><%= link_to u.username, user_profile_path(:user => u.id) %></td>
			<td align="center"><%= u.posts.count %></td>
		</tr>
		<% list_num = list_num + 1 %>
		<% if list_num > 10; break; end %>
	<% end %>
</table>
</div>

app/views/navigation/about.html.erb
<body class="main">
<div id="about_wrapper">

<h1>Welcome to HillHeroes.com!</h1>
</br>

	<p>My name is Matt Dick (like the appendage).  I lived on the Hill for 5 years, 3 of those years as an RA.  The concept for HillHeroes.com was born in September, 2011 from the minds of me and my RA counterpart, Erik Hilkey.  Initially, the plan was to generate a subtle chaos on the Hill by providing its residents with the inside scoop on policy enforcement and how to break rules while avoiding trouble.  Back then, Erik and I were the “Hill Heroes,” out to save the Hill from boredom and the iron first of ORL.  And while <%= link_to "that content is available within this site", "/forums/forums/1" %>, HillHeroes.com has evolved and gained more utility while at the same time shifting the spotlight from ourselves to the real Hill Heroes: you, the residents of the Hill.  You are the Hill Heroes because with each new textbook listing and forum post, you are making Hill life more enjoyable.  Below, you will discover the functionality that has been added to the site.  If you like what you see, be sure to <%= link_to "become a Hill Hero", new_user_registration_path %> and set up your profile (a 60 second endeavor) to continue making this site as effective as possible.</p>

<h3>Community and Collaboration</h3>

	<p>The Hill is packed with the best and brightest individuals in California and beyond.  Everyone has their own stories, wisdom, and inside information for the sharing, but after those first couple weeks, students become busy and comfortable inside their bubble of friends, cutting themselves off from all there is to gain from the bright people around them.  That being said, HillHeroes.com has been set up with a forum for Hill residents to communicate and share information with one another.  Take a look through the <%= link_to "forum", forem.forums_path %> to get a feel for the sort of information that is being created every day.</p>


<h3>Textbooks</h3>

	<p>The textbook market is gigantic, and the internet provides plenty of ways to buy and sell books.  Hill Heroes does it better.</p>

	<ul>
		<li>RELEVENCE: The population of the Hill is predominantly first and second year students all taking the same lower division courses at different times.  By spring quarter, an army of textbook and course reader clones will have amassed, two-thirds of which sit in bookshelves to convince your folks you are actually working when they visit.  Finding exactly the book you need in the <%= link_to "textbook exchange", find_books_path %> is easy because it was likely <em>just used for the same class you’ll be taking</em>.  And unless your professor wrote the book and enjoys stealing money from his students, the edition probably hasn’t changed from the last quarter.</li></br>

		<li>CONVENIECE: The <%= link_to "textbook exchange", find_books_path %> allows you to find textbooks and course readers as sorted by UCLA specific classes.  Furthermore, the building of the book seller is available in the <%= link_to "textbook exchange", find_books_path %>.  Buying a textbook could be as easy as walking down the Hill or even up a flight of stairs!</li></br>
		 
		<li>FREE: Yes, listing your textbooks in the exchange does not cost you a dime.</li>
	</ul>

<h3>Suggestions/Comments</h3>

	<p>The goal of this site is to provide tools necessary for residents of the Hill to have as positive an experience living here as possible.  There is a <%= link_to "forum for comments and suggestions", "/forums/forums/6" %> as they relate to this site and I encourage anyone and everyone to pitch in and share their ideas to make for a better user experience here at HillHeroes.com.</p>

</br>

<div id="ending">
	Thanks for reading,</br>
		Matt Dick
</div>

</div>
</body>

app/views/navigation/add_major_minor.js.erb
page.replace_html "testDiv", render :partial => "/navigation/add_major_minor"

app/views/navigation/alt_homepage.html.erb
<body class="main">
<div id="homepage_wrapper">
	<!-- <span class="title">Hill Heroes</span> -->
	<a href="/homepage"><span id="logo"><%= image_tag "/logo.png" %></span></a>
	<span class="subtitle"><%= @rand_subtitle %></span>
	
	<div class="close_resources">
		<div id="navigation">
			<span id="about_link" ><%= link_to "About", "", :remote => true %> | 
			<a href="/forums">Forum</a></span> | 
			<span id="dining_menu_link"><%= link_to "Dining Menu", homepage_path, :remote => true %></span> | 
			<%= link_to "Textbooks", find_books_path %> | 
			<%= link_to "Classmates", classmates_path %> | 
			<%= link_to "Test Bank", test_bank_path %> | 
			<%= link_to "Resources", "", :remote => true, :id => "resources_link" %>
		</div>

		<div id="resources_panel">
			<ul>
				<li><%= link_to "Submit a Maintenance Request", "http://www.housing.ucla.edu/workorder/", :target => "_blank" %></li>
				<li><%= link_to "Deposit to BCard", "https://secure.bruincard.ucla.edu/bcw/app/webdeposit/TransactionRequest.aspx", :target => "_blank" %></li>
				<li><%= link_to "CEC Free Sneaks", "http://campuseventsblog.com/category/films/", :target => "_blank" %></li>
				<li><%= link_to "Melnitz Screenings", "http://gsa.asucla.ucla.edu/melnitz", :target => "_blank" %></li>
				<li><%= link_to "Student Jobs", "http://www.asucla.ucla.edu/jobs/student.asp", :target => "_blank" %></li>
				<li><%= link_to "Career Center", "https://secure.career.ucla.edu/BruinViewLogin/Login.aspx", :target => "_blank" %></li>
			</ul>
		</div>
	</div>
	
	<div class="left">
			<div id="accordion">
				<h3 id="top" class="cyclotron"><a href="#">Welcome!</a></h3>
				<div id="height" style="padding: 0 5px 0 5px;">
					<div id="roadmap_link"><div id="roadmap_link_1"><%= link_to "HILL RESIDENT STUDENT SURVIVAL GUIDE", "" %></div> <div id="roadmap_link_2"><%= link_to "your roadmap around the rules.", "" %></div></div>
				</div>
				<h3 id="about"><a href="#">About</a></h3>
				<div>
					<div id="about_title">Hill resident? Hill Heroes has you covered:</div>
					<img src="doItLive.png" />
					<div id="about_list">
						<ul>
							<li>-Download old quizzes, midterms, and finals from the <%= link_to "Test Bank", test_bank_path %></li>
							<li>-Cut out the middle man and <%= link_to "exchange textbooks", find_books_path %> with students living right here on the Hill</li>
							<li>-See <span id="pseudo_dining_menu_link"><%= link_to "what's for dinner", "", :remote => true %></span></li>
							<li>-And <%= link_to "more", "/forums" %>!</li>
						</ul>
					</div>
				</div>
			</div>
	</div>
	
	<div class="right">
		<div id="top_posters">
			<%= render :partial => "test_bank_uploads" %>
		</div>
		<div id="top_posters">
			<%= render :partial => "newest_users" %>
		</div>
	</div>

	<div id="background_image"><img src="superbear.jpg" /></div>

	<div id="dining_menu"><%= render :partial => "/navigation/dining" %></div>
</div>
</body>

app/views/navigation/hot_topics.html.erb
<!-- Hot topics listings -->

Here are the hot topics

app/views/navigation/newest_topics.html.erb
<form>
    <div id='row1'><label>Major:</label><input type='text' id='major1' name='major1'></div>
    <div id='row2'><label>2nd Major:</label><input type='text' id='major2' name='major2'></div>
     <div id='row3'><label>3rd Major:</label><input type='text' id='major3' name='major3'></div>
</form>
<a href='#' id='moremajors'>add more majors</a>

app/views/navigation/sandbox.html.erb
<%= stylesheet_link_tag "sandbox" %>

Manage Classes
</br></br></br>


<body class="main">
	<span id="quarter">
		<b>Fall 2012</b>
	</span>
	
	<div id="classes">
		<table>
			<col width="800" />
			<col width="200" />
				<%= render :partial => "my_courses" %>
		</table>
	</div>
	
	<div>
		<div><button id="show_fields">Add Classes</button></div>
	</div>
	
	<div id="selections">
		<%= form_tag(add_course_to_quarter_path, :remote => true) do %>
			<%= collection_select(:new_class, :field, @fields, :id, :title, {:prompt => "Fields..."}, {:id => "field_select"}) %></br>
			<%= collection_select(:new_class, :course, @courses, :id, :title, {:prompt => "Select A Field From The List Above"}, {:id => "course_select"}) %>
			<%= submit_tag("Add") %>
		<% end %>
	</div>
</body>

</br></br></br>

app/views/navigation/sandbox.js.erb
$('#course_select').html("");
$('#course_select').html("<%= escape_javascript(options_from_collection_for_select(@course_list, :id, :title)) %> ");